# Generated by Django 4.0.5 on 2022-11-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leavetype_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='auto',
            field=models.BooleanField(default=True),
        ),
    ]
