# Generated by Django 4.2.1 on 2023-07-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_rename_edd_foem_leaveapplication_edd_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='resumption_initiated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
