# Generated by Django 4.2.1 on 2023-08-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_leaveapplication_resumption_initiated'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='requires_hcs_approval',
            field=models.BooleanField(default=False),
        ),
    ]
