# Generated by Django 4.0.5 on 2022-06-07 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_rename_parmanent_home_address_address_permanent_home_address_and_more'),
        ('leave', '0012_rename_dclineleaveapplication_declineleaveapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contact.state'),
            preserve_default=False,
        ),
    ]
