# Generated by Django 4.0.5 on 2022-06-21 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_rename_parmanent_home_address_address_permanent_home_address_and_more'),
        ('leave', '0013_leaveapplication_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='approval_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leave.approval'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contact.state'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leave.leaveduration'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leave.leavetype'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leave.leaveapplicationstatus'),
        ),
    ]
