# Generated by Django 4.0.5 on 2022-06-28 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_alter_leaveapplication_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveresumption',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='leaveresumption',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='leaveresumption',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='leaveresumption',
            name='approval_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='leave.approval'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveresumption',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leave.leaveapplicationstatus'),
        ),
    ]
