# Generated by Django 4.0.5 on 2022-06-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0015_remove_leaveresumption_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveresumption',
            name='status',
        ),
    ]
