# Generated by Django 4.0.5 on 2022-06-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0016_remove_leaveresumption_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveresumption',
            name='approval_status',
        ),
    ]
