# Generated by Django 4.0.5 on 2022-06-28 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0017_remove_leaveresumption_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveresumption',
            name='recommended_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
