# Generated by Django 4.0.5 on 2022-06-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0020_leaveresumption_resumption_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='resumption_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.resumptionapproval'),
        ),
    ]
