# Generated by Django 4.0.5 on 2022-07-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0022_remove_leaveresumption_resumption_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
