# Generated by Django 4.0.5 on 2022-07-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0023_leaveapplication_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='last_update',
            new_name='last_updated',
        ),
    ]
