# Generated by Django 4.0.5 on 2022-08-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_remove_gradelevel_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentdetails',
            name='ippis_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
