# Generated by Django 4.2.1 on 2023-06-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_employmentdetails_ippis_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentdetails',
            name='confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmentdetails',
            name='date_of_appt_with_fmc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmentdetails',
            name='first_appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmentdetails',
            name='present_appt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmentdetails',
            name='qualifications',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='employmentdetails',
            name='rank',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
