# Generated by Django 4.0.5 on 2022-07-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_alter_employmentdetails_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Head',
        ),
    ]
