# Generated by Django 4.0.3 on 2022-06-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_nationality_contact_state_of_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='state_of_origin',
        ),
        migrations.AlterField(
            model_name='address',
            name='local_goverment_area_of_residence',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='parmanent_home_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='residential_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_of_next_of_kin',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='local_goverment_area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='next_of_kin',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='next_of_kin_phone_no',
            field=models.CharField(max_length=150),
        ),
    ]
