# Generated by Django 4.0.3 on 2022-06-06 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contact_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state_of_residence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contact.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.country'),
        ),
        migrations.AddField(
            model_name='contact',
            name='state_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.state'),
        ),
    ]
