# Generated by Django 4.0.3 on 2022-06-06 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contact_next_of_kin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='parmanent_home_address',
            new_name='permanent_home_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='local_goverment_area_of_residence',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='local_goverment_area',
        ),
        migrations.AddField(
            model_name='address',
            name='local_government_area_of_permanent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lga', to='contact.localgovernmentarea'),
        ),
        migrations.AddField(
            model_name='address',
            name='local_government_area_of_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.localgovernmentarea'),
        ),
        migrations.AddField(
            model_name='address',
            name='state_of_permanent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='contact.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='local_government_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.localgovernmentarea'),
        ),
    ]
