# Generated by Django 4.0.5 on 2022-07-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_address_user_alter_contact_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mobile_no',
            new_name='phone1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
