# Generated by Django 4.0.5 on 2022-08-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_department_alter_user_directorate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ippis_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
