# Generated by Django 4.0.5 on 2022-08-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_grade_level_remove_user_ippis_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='has_unit',
            field=models.BooleanField(default=True),
        ),
    ]
