# Generated by Django 4.0.5 on 2022-10-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Head',
        ),
    ]
