# Generated by Django 4.0.3 on 2022-06-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_phone_number_one_user_phone_number_two_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number_one',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number_two',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sub_unit',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
