# Generated by Django 4.2.1 on 2023-08-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_other_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='reports_to_cmd',
            field=models.BooleanField(default=False),
        ),
    ]
