# Generated by Django 4.0.5 on 2022-07-04 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_usergroup_user_user_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_head_of_sub_unit', models.BooleanField(default=False)),
                ('is_head_of_unit', models.BooleanField(default=False)),
                ('is_head_of_dept', models.BooleanField(default=False)),
                ('is_head_of_directorate', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
