# Generated by Django 4.0.5 on 2022-07-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='head',
            name='is_head_of_sub_unit',
        ),
    ]
