# Generated by Django 4.0.5 on 2022-07-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_head_is_head_of_sub_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='head',
            name='is_cmd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='file_number',
            field=models.IntegerField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='other_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
