# Generated by Django 4.0.5 on 2022-07-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_head_is_cmd_alter_user_file_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file_number',
            field=models.IntegerField(unique=True),
        ),
    ]
